env:
  browser: true
  es6: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "indent": ["warn", 4],
  "semi": ["warn", "always"],
  "brace-style": ["warn", "stroustrup"]
}
